backend:
  name: git-gateway
  branch: main
media_folder: "public/src/images"
public_folder: "src/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogs"
    create: true
    slug: "{{slug}}"
    # fields:
    #   - { label: "Title", name: "title", widget: "string" }
    #   - { label: "Description", name: "description", widget: "string" }
    #   - { label: "Author", name: "author", widget: "string" }
    #   - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
    #   - { label: "Featured Image", name: "image", widget: "image" }
    #   - { label: "Featured Image2", name: "image2", widget: "image" }
    #   - { label: "Image caption", name: "imageAlt", widget: "string" }
    #   - { label: "Body", name: "body", widget: "markdown" }

fields:
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Description", name: "description", widget: "string" }
  - { label: "Author", name: "author", widget: "string" }
  - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
  - { label: "Subheading 1", name: "subheading1", widget: "string" }
  - { label: "Paragraph 1", name: "paragraph1", widget: "markdown" }
  - { label: "Image 1", name: "image1", widget: "image" }
  - { label: "Image caption 1", name: "imageAlt1", widget: "string" }
  - { label: "Subheading 2", name: "subheading2", widget: "string" }
  - { label: "Paragraph 2", name: "paragraph2", widget: "markdown" }
  - { label: "Image 2", name: "image2", widget: "image" }
  - { label: "Image caption 2", name: "imageAlt2", widget: "string" }
